version: '3'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: "uvicorn wsgi:application --reload --host 0.0.0.0 --port 8000"
    volumes:
      - .:/my_cookbook
    ports:
      - "8000:8000"
    # depends_on:
    #   - db


  # db:
  #   image: postgres:latest
  #   restart: always
  #   env_file:
  #     - ".env"
  #   volumes:
  #     - postgresql_db_data:/var/lib/postgresql/data/
  #   expose:
  #     - 5432
  #   ports:
  #     - 5432:5432

networks:
  default:
    driver: bridge

# volumes:
#   postgresql_db_data:

