"""Add RecipeItem model

Revision ID: 7f30e2286c5f
Revises: ad75432e6e33
Create Date: 2023-06-19 03:27:52.973856

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7f30e2286c5f"
down_revision = "ad75432e6e33"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipeitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipe.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipeitem_id"), "recipeitem", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipeitem_id"), table_name="recipeitem")
    op.drop_table("recipeitem")
    # ### end Alembic commands ###
