"""User Recipe Relationship

Revision ID: ad75432e6e33
Revises: e4171629d5ed
Create Date: 2023-06-13 21:48:48.541714

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ad75432e6e33"
down_revision = "e4171629d5ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipe", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "recipe", "user", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "recipe", type_="foreignkey")
    op.drop_column("recipe", "owner_id")
    # ### end Alembic commands ###
