"""Recipe Model

Revision ID: e4171629d5ed
Revises: c3d344f2c314
Create Date: 2023-06-13 20:25:02.165958

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e4171629d5ed"
down_revision = "c3d344f2c314"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("duration", sa.String(), nullable=True),
        sa.Column("serves", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recipe_id"), "recipe", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recipe_id"), table_name="recipe")
    op.drop_table("recipe")
    # ### end Alembic commands ###
