"""Alter Step relationship

Revision ID: f948b74e8926
Revises: 43ee2baaa050
Create Date: 2023-06-19 13:03:04.106175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f948b74e8926'
down_revision = '43ee2baaa050'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('recipe_item_id', sa.Integer(), nullable=True))
    op.drop_constraint('step_recipe_id_fkey', 'step', type_='foreignkey')
    op.create_foreign_key(None, 'step', 'recipeitem', ['recipe_item_id'], ['id'])
    op.drop_column('step', 'recipe_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'step', type_='foreignkey')
    op.create_foreign_key('step_recipe_id_fkey', 'step', 'recipe', ['recipe_id'], ['id'])
    op.drop_column('step', 'recipe_item_id')
    # ### end Alembic commands ###
