name: Rodar Testes

on:
  # pull_request:
  #   branches:
  #     - main
  push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Atualizar Repo
        uses: actions/checkout@v2
          
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path:  |
            requirements-dev.txt

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar Testes
        run: python -m unittest discover -v